version: "3"
services:
  backend:
    build: ./Backend-SHBootcamp
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - ./.env
  frontend:
    build: ./Frontend-SHBootcamp
    ports:
      - "3000:3000"
    restart: always
